### ISSUE TITLE
Android suiteName compare null with empty string (0.99)

### ISSUE THREAD

**Issue by ajfaura** [apla/me.apla.cordova.app-preferences#100]
Cordova is getting version 0.99 if no version is specified at package.json, instead of 0.7.7.
This version (0.99) doesn't work at all at least in Android. Please fix this issue.

Plugin version:
  - [x] released version: 0.99

Toolchain:
  - [x] Ionic

Platforms affected:
  - [x] Android

What the scope of your problem:
  - [x] Suites

**Comment by ajfaura** [comment]
--> Ionic 2 cli

**Comment by ajfaura** [comment]
There bug is at execute method

`String suiteName = options.optString("suiteName");

		SharedPreferences sharedPrefs;
		if (suiteName != null) {
			sharedPrefs = cordova.getActivity().getSharedPreferences(suiteName, Context.MODE_PRIVATE);
		} else {
			sharedPrefs = PreferenceManager.getDefaultSharedPreferences(cordova.getActivity());
		}`

suiteName is never null. Correct code: String suiteName = options.optString("suiteName", null);

**Comment by apla** [comment]
fixed with version `0.99.1`

**Comment by apla** [comment]
No feedback for over two months, closing
