### ISSUE TITLE
Failed to install 'cordova-plugin-app-preferences': TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by miparnisari** [apla/me.apla.cordova.app-preferences#101]
Please specify your environment :

Plugin version:
  - [x] released version: 0.99.0
  - [ ] repository master

Toolchain:
  - [ ] Cordova cli
  - [ ] Phonegap cli
  - [ ] Phonegap cloud
  - [x] Ionic
  - [ ] Other: _____

Platforms affected:
  - [x] Android
  - [ ] iOS/macOS
  - [ ] LocalStorage fallback for browser and blackberry
  - [ ] Windows and Windows Phone 8.1 and later
  - [ ] Windows Phone 8 and earlier (deprecated)

What the scope of your problem:
  - [x] General functionality (store/fetch/remove/clearAll)
  - [ ] Suites
  - [ ] Cloud synchronization and events

Please describe the issue:

When running the command `ionic platform add android` I get this error:
```javascript
Installing "cordova-plugin-app-preferences" for android
unhandled exception [TypeError: Cannot convert undefined or null to object]
Failed to install 'cordova-plugin-app-preferences':TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at validateFormat (C:\Users\miparnisari\...\plugins\cordova-plugin-app-preferences\bin\lib\settings.js:35:38)`
```

**Comment by apla** [comment]
Plugin installation routine cannot parse `app-settings.json`. Seems like something wrong with file contents

**Comment by apla** [comment]
No reply for over two months, closing
