### ISSUE TITLE
Unable to fetch by key on Android

### ISSUE THREAD

**Issue by JoeKomputer** [apla/me.apla.cordova.app-preferences#103]
Please specify your environment :

Plugin version:
  - [x] released version: 0.99.0
  - [x] repository master

Toolchain:
  - [ ] Cordova cli
  - [ ] Phonegap cli
  - [ ] Phonegap cloud
  - [x] Ionic
  - [ ] Other: _____

Platforms affected:
  - [x] Android
  - [ ] iOS/macOS
  - [ ] LocalStorage fallback for browser and blackberry
  - [ ] Windows and Windows Phone 8.1 and later
  - [ ] Windows Phone 8 and earlier (deprecated)

What the scope of your problem:
  - [x] General functionality (store/fetch/remove/clearAll)
  - [ ] Suites
  - [ ] Cloud synchronization and events

Please describe the issue:
fetch is always returning null in android. It never makes it inside of this if statement(line:204 AppPreferences.java):
`if (sharedPrefs.contains(key)) {`
Even though the keys do exist, it is unable to find them in sharedPrefs.

Tested with both cordova 5.4.0 and 6.1.1, and Android 4.4.2 and 5.1.1.

**Comment by apla** [comment]
Same as #100
