### ISSUE TITLE
placing xml file?

### ISSUE THREAD

**Issue by nikolasr200** [apla/me.apla.cordova.app-preferences#11]
hi, i can't workout where the xml file with the value pairs should be placed..
i m getting an error [aapt] D:\path\to\project\platforms\android\res\xml\pref_ge
neral.xml:9: error: Error: No resource found that matches the given name (at 'en tries' with value '@array/measurementunit'). [aapt] D:\path\to\project\platforms\android\res\xml\pref_ge neral.xml:9: error: Error: No resource found that matches the given name (at 'en tryValues' with value '@array/measurementunitValues').

http://stackoverflow.com/questions/26205674/apache-cordova-application-preferences-apla

**Comment by apla** [comment]
Now generated preferences file is placed automatically. You don't need to do anything.

**Comment by nikolasr200** [comment]
module.js:340
    throw err;
          ^
Error: Cannot find module 'myprojectpath\plugins\me.apla.co
rdova.app-preferences\bin\build-app-settings.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by apla** [comment]
Seems I can close this issue because of #39

**Comment by nikolasr200** [comment]
Yes you updated several instructions as well so this was addressed.
