### ISSUE TITLE
nothing is getting recognised in ios

### ISSUE THREAD

**Issue by dwissmann** [apla/me.apla.cordova.app-preferences#117]
Issue:
I am very sorry to write this (it is my first app using cordova) but I cannot - for the live of me - figure out how to use this plug in. I installed the plugin via cordova. Then I updated the cordova-plugin.js file with the following entries:
`{
        "id": "cordova-plugin-app-preferences.AppPreferences",
        "file": "plugins/cordova-plugin-app-preferences/www/apppreferences.js",
        "pluginId": "cordova-plugin-app-preferences"
    },
    {
        "id": "cordova-plugin-app-preferences.AppPreferenceTask",
        "file": "plugins/cordova-plugin-app-preferences/www/task/AppPreferences.js",
        "pluginId": "cordova-plugin-app-preferences"
    }`
I hope that was correct! Then I added the following snipped into my index.html file:
`prefs = cordova.plugins.appPreferences;`

Then, I added a test function that is called via a button:
`function testMobileApp() {
    $("#windowTitle").append('<h3>testing the mobile app</h3>');

    prefs.fetch (function(rt){
        $('#messageClient').empty();
        $('#messageClient').append("your server preference is " + rt);
        $('#messageClient').trigger('create');
    }, fail, 'server');
}`

and I get the error: 

> TypeError: prefs.fetch is not a function. (In 'prefs.fetch', 'prefs.fetch' is undefined)

am I doing everthing totally false? Would you please help me

Please specify your environment

Plugin version:
  - [ ] released version: _____
  - [ ] repository master

Toolchain:
  - [x ] Cordova cli
  - [ ] Phonegap cli
  - [ ] Phonegap cloud
  - [ ] Ionic
  - [ ] Other: _____

Platforms affected:
  - [ ] Android
  - [ x] iOS/macOS
  - [ ] LocalStorage fallback for browser and blackberry
  - [ ] Windows and Windows Phone 8.1 and later
  - [ ] Windows Phone 8 and earlier (deprecated)

What the scope of your problem:
  - [x ] General functionality (store/fetch/remove/clearAll)
  - [ ] Suites
  - [ ] Cloud synchronization and events
  - [ ] Preferences pane generation and display

**Comment by dgadelha** [comment]
Have you included `cordova.js` in your web page?

**Comment by dwissmann** [comment]
That was it - the new version generates a new Cordova.js file and distributes it - I was linking to my own file instead of the one generated in the root of the project. Thanks - took a lot of digging

Dom Wissmann
