### ISSUE TITLE
How to display config titles according to device language using app-settings.json file

### ISSUE THREAD

**Issue by tonirilix** [apla/me.apla.cordova.app-preferences#128]
Issue:
_____
How can I use app-setting.json in a way that the titles of each item display according to device language?

Please specify your environment

Plugin version:
  - [X] released version: 0.99.3
  - [ ] repository master

Toolchain:
  - [ ] Cordova cli
  - [ ] Phonegap cli
  - [ ] Phonegap cloud
  - [X] Ionic
  - [ ] Other: _____

Platforms affected:
  - [X] Android
  - [X] iOS/macOS
  - [ ] LocalStorage fallback for browser and blackberry
  - [ ] Windows and Windows Phone 8.1 and later
  - [ ] Windows Phone 8 and earlier (deprecated)

What the scope of your problem:
  - [ ] General functionality (store/fetch/remove/clearAll)
  - [ ] Suites
  - [ ] Cloud synchronization and events
  - [X] Preferences pane generation and display

**Comment by marcusforsberg** [comment]
@tonirilix Did you find a solution for this?

**Comment by tonirilix** [comment]
@marcusforsberg unfortunately no. I had to create my own screen. The release date was too close. 
Sorry, I forgot to say why I closed it.
