### ISSUE TITLE
private mode

### ISSUE THREAD

**Issue by mrmoses** [apla/me.apla.cordova.app-preferences#20]
It would be nice to be able to set the preference file as private.

For Android:
`SharedPreferences sharedPrefs = PreferenceManager.getDefaultSharedPreferences(cordova.getActivity(), Context.MODE_PRIVATE);`

Not sure if or how other systems offer private mode.

**Comment by apla** [comment]
>Operating mode. Use 0 or MODE_PRIVATE for the default operation, MODE_WORLD_READABLE and MODE_WORLD_WRITEABLE to control permissions. The bit MODE_MULTI_PROCESS can also be used if multiple processes are mutating the same SharedPreferences file. MODE_MULTI_PROCESS is always on in apps targeting Gingerbread (Android 2.3) and below, and off by default in later versions.

from [here](http://developer.android.com/reference/android/content/Context.html#getSharedPreferences%28java.lang.String,%20int%29)
