### ISSUE TITLE
Integrate the plugin in ngCordova 

### ISSUE THREAD

**Issue by nabiltntn** [apla/me.apla.cordova.app-preferences#21]
Hi,

Do you have any plans to integrate the plugin in ngCordova. The current selected plugin wrapper for app preferences does not work properly.
You can check the issue below  : 
https://github.com/driftyco/ng-cordova/issues/473

Thanks !

**Comment by apla** [comment]
Can you create a test for your issue? In your issue just info about cordova preferences plugin
