### ISSUE TITLE
cordova.exec.bind [undefined]

### ISSUE THREAD

**Issue by kwetzakwak** [apla/me.apla.cordova.app-preferences#27]
On an old android device, I have "TypeError: Resulst of expression 'cordova.exec.bind' [undefined] is not a function. at file:///android_[...]apppreferences.js:29

That error refers to: 
<strong>platform.nativeExec = cordova.exec.bind (cordova);</strong>

It prevents "deviceready" event to be fired...

**Comment by apla** [comment]
please specify what version you're using for:
cordova
cordova-android

**Comment by kwetzakwak** [comment]
I'm using:

Cordova 4.3.0,
the problem occurs on android 2.2.1, 2.3.5, but does not on 2.3.7+

Maybe the properties wern't the same ?

**Comment by kwetzakwak** [comment]
Well, Cordova 5.0 doesn't support api < 10, so I guess the issue isn't actually one ^^
