### ISSUE TITLE
prefs.fetch(ok, fail, 'key') returns array if key is not found (iOS 8)

### ISSUE THREAD

**Issue by mirko77** [apla/me.apla.cordova.app-preferences#29]
I am trying the plugin on iOS 8.1.2, Cordova iOS 3.8

when I do `prefs.fetch(ok, fail, 'key');` and key does not exist, the `ok` callback is called with an array as `value` so I need to do an extra check only on iOS to make it work

**Comment by apla** [comment]
Fixed some issues for non-existing keys. Please install new version from github repo and report does it work for you.

**Comment by jacobg** [comment]
I see a similar issue. If I fetch a non-existing key in iOS, the ok handler is called with value null. On Android, the fail handler is called. Based on documentation, on iOS the fail handler should be called.

**Comment by apla** [comment]
@jacobg can you provide test case? what version you're using? just launched test for android and every test is pass. according to the [test source](../tree/master/src/test.js#L78) (lines 48 and 78), there is a check for this issue.

**Comment by apla** [comment]
No response, have test for this, test passing
