### ISSUE TITLE
Support for Cordova 5.0.0?

### ISSUE THREAD

**Issue by strille** [apla/me.apla.cordova.app-preferences#31]
Any plans to add support for Cordova 5.X in the near future? 

This plugin looked very promising, but according to the README which says it supports Cordova 3.x and my initial testing it's not working very well with Cordova 5.0.0.

In Windows, I have managed to call `plugins.appPreferences.store()` successfully, but when I retrieve the key value with `plugins.appPreferences.fetch()` I always get boolean `true` back no matter what value I stored.

In iOS 8 `appPreferences` isn't even available on the `plugins` object.

Regards, 
Mattias

**Comment by apla** [comment]
I'll check windows issue soon, but cannot confirm iOS bug. Try to reinstall plugin for iOS

**Comment by apla** [comment]
windows bug confirmed and fixed with d8063248db06342eac0029637ab19fc5e1279230
