### ISSUE TITLE
The latest version from master does not work on Android, only on iOS

### ISSUE THREAD

**Issue by ishaigor** [apla/me.apla.cordova.app-preferences#32]
Had to fork off the latest tag to fix the following:
    [javac] Compiling 32 source files to /Users/ishaigorodsky/Workspace/git/ceMobileApp/platforms/android/ant-build/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /Users/ishaigorodsky/Workspace/git/ceMobileApp/platforms/android/src/me/apla/cordova/AppPreferences.java:18: error: cannot find symbol
    [javac] import me.apla.cordova.AppPreferencesActivity;
    [javac]                       ^
    [javac]   symbol:   class AppPreferencesActivity
    [javac]   location: package me.apla.cordova
    [javac] /Users/ishaigorodsky/Workspace/git/ceMobileApp/platforms/android/src/me/apla/cordova/AppPreferences.java:82: error: cannot find symbol
    [javac] 			Intent i = new Intent(cordova.getActivity(), AppPreferencesActivity.class);
    [javac] 			                                             ^
    [javac]   symbol: class AppPreferencesActivity
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors
    [javac] 3 warnings

**Comment by apla** [comment]
You're too fast! Try latest version.

**Comment by ishaigor** [comment]
Back at you :+1: 
I was not counting on it fixed right away.
