### ISSUE TITLE
iOS use: [NSUserDefaults initWithSuiteName:@"<configurable_name">

### ISSUE THREAD

**Issue by weiner** [apla/me.apla.cordova.app-preferences#34]
Hi,

I would love to have the option to use this module in combination with a iOS Extension. 
To share NSUserDefaults between the App and a Extenion you need to use the NSUserDefaults initWithSuiteName.

https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/
NSUserDefaults_Class/index.html#//apple_ref/occ/instm/NSUserDefaults/initWithSuiteName:

**Comment by oktapodi** [comment]
This is quite easy to do.. all you have to do is change this line 
```
NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
```
to
```
NSUserDefaults *defaults = [[NSUserDefaults alloc] initWithSuiteName:@"group.company.appname"];
```
in  AppPreferences.m

It would be great to have it implemented by default but for those in need of it right now you can do it yourself by changing that one line. I think it appears in 3 different places in the same file.

**Comment by apla** [comment]
just got a clever idea how to implement this.

please checkout latest version

how to use:

```javascript
var suitePrefs = plugins.appPreferences.iosSuite ("suiteName");
suitePrefs.fetch (...);
suitePrefs.store (...);
```

**Comment by apla** [comment]
No response
