### ISSUE TITLE
Preferences not accessable from java.

### ISSUE THREAD

**Issue by ksabariraj** [apla/me.apla.cordova.app-preferences#42]
Hi,
Thanks for the plugin.

I set preference and I can able to read using plugin. But, when I tried to access the same preferences from Java code, its not available. Can you please guide me on this.

**Comment by apla** [comment]
Are you using

```java
SharedPreferences sharedPrefs = PreferenceManager.getDefaultSharedPreferences(cordova.getActivity());
```

to get the shared preferences? If yes, please give me snippet of code which confirms the issue.

**Comment by ksabariraj** [comment]
Hey,

Sorry for the delay response.

Please see the below code. ( I used same as in SplashScreen.java )
preferences.getInteger("UserID", 0);


When I tried to print the application preference, I got only the preference which I mention in config file.

Thanks,
Sabari.

**Comment by ksabariraj** [comment]
Hey,

Its working after creating sharedPref object as you mentioned.

SharedPreferences sharedPrefs = PreferenceManager.getDefaultSharedPreferences(cordova.getActivity());

Thanks,
Sabari.
