### ISSUE TITLE
Settings resources should be generated in an `afterPrepare` hook

### ISSUE THREAD

**Issue by speigg** [apla/me.apla.cordova.app-preferences#46]
This way no extra steps are necessary.

**Comment by micky2be** [comment]
+1

**Comment by SomaticIT** [comment]
+1

**Comment by SomaticIT** [comment]
An easy way to do this is to add a `hook` tag to __plugin.xml__ file :
````xml
<hook type="after_prepare" src="bin/build-app-settings.js" />
````

Source: https://cordova.apache.org/docs/en/edge/plugin_ref/spec.html#link-23

**Comment by SomaticIT** [comment]
Done in #50.
