### ISSUE TITLE
App preference activity theme

### ISSUE THREAD

**Issue by mohitmayank** [apla/me.apla.cordova.app-preferences#52]
as of now when i do perf.show(); the activity window is material black (on android) . is there any way it can be customized using some preference?

**Comment by apla** [comment]
Generated [activity preference code](https://github.com/apla/me.apla.cordova.app-preferences/blob/master/src/android/AppPreferencesActivity.template) is very simple, customization is on developer side.

Documentation on Activity Preferences [here](http://developer.android.com/reference/android/preference/PreferenceActivity.html).
