### ISSUE TITLE
Settings.bundle file for Android?

### ISSUE THREAD

**Issue by shredmer** [apla/me.apla.cordova.app-preferences#55]
For starters, I do not have the dev experience most of you have posting here but I am having trouble getting this plugin to work for Android and figured this is where I would get the most informative response.

Yesterday I installed the plugin and was able to read from my Root.plist file in the Settings.bundle file for iOS. To do so required copying the Settings.bundle into my Xcode project.

Is there a similar step or file to copy over for Android? I have not defined a key or value for android so I assume this is the issue. Also, I receive the following error while trying to emulate for Android:

```
Error Code:
  	1
  Output:
  	/Users/shredmer/Applications/NoHarm_Basic2/platforms/android/build/intermediates/res/debug/xml/apppreferences.xml:2: error: Error: No resource found that matches the given name (at 'entries' with value '@array/apppreferences_lang').
  	
  	/Users/shredmer/Applications/NoHarm_Basic2/platforms/android/build/intermediates/res/debug/xml/apppreferences.xml:2: error: Error: No resource found that matches the given name (at 'entryValues' with value '@array/apppreferences_langValues').
```

Thank you for your help.

**Comment by lakano** [comment]
Hello,

I have the same error too :(
Regards,

**Comment by lakano** [comment]
@shredmer To not be blocked, you can get an old version:
```
git clone --single-branch -b "version/0.6.1" https://github.com/apla/me.apla.cordova.app-preferences.git path/where/you/want/cordova-app-preferences-0.6.1
```
and then in your project path:
```
ionic plugin add /where/you/want/cordova-app-preferences-0.6.1
```

Regards,

**Comment by shredmer** [comment]
Thanks, that fixed the build error. However, I am still having difficulty reading the settings value for Android. Which file are you using for the settings? Is it android/res/xml/apppreferences.xml ? If so how did you get it to read from the file correctly?

**Comment by LightZam** [comment]
i used this workaround

cordova plugin add cordova-plugin-app-preferences@0.7.1

**Comment by bitflower** [comment]
@LightZam thanks, confirmed. Got it running with 0.7.1

Be sure to
ionic plugin rm cordova-plugin-app-preferences
ionic platform rm YOUR-OS

and re-add both afterwards

**Comment by bitflower** [comment]
I can confirm that this works as of v0.7.4.

**Comment by apla** [comment]
@shredmer have you tried 0.7.4?

**Comment by shredmer** [comment]
Yes, 0.7.4 builds fine. Thank you

**Comment by sylfree9999** [comment]
@shredmer Hi, I have found your problem in [stackoverflow()] about the app integration with Airwatch. I don't have enough reputation so I have no choice but to ask here. sorry ! I am wondering if you have successfully solve this issue? Do you use Airwatch App Wrapping or SDK or ACE?(http://stackoverflow.com/questions/33400087/retrieving-username-through-mdm-by-configuring-enterprise-app-preferences-airwa)
