### ISSUE TITLE
Settings.bundle for iOS is put in the wrong folder

### ISSUE THREAD

**Issue by bitflower** [apla/me.apla.cordova.app-preferences#60]
I believe Settings.bundle is supposed to live inside platform/ios/MYPROJECT/Resources/ not platform/ios/MYPROJECT/

After adding the plugin I can't build because of this, moving the file to /Resources resolves the problem:
** BUILD FAILED **
The following build commands failed:
	CpResource MYPROJECT/Resources/Settings.bundle build/emulator/MYPROJECT.app/Settings.bundle
(1 failure)

![bildschirmfoto 2015-11-11 um 06 19 06](https://cloud.githubusercontent.com/assets/6666636/11084501/575ad072-883c-11e5-9d2e-891f22087103.png)

Bug of npm xcode?

**Comment by shredmer** [comment]
I can confirm this as well. After generating the bundle, it is required to be moved to the Resources folder.
