### ISSUE TITLE
Settings.bundle on iOS not updated from app-settings.json, Android works

### ISSUE THREAD

**Issue by bitflower** [apla/me.apla.cordova.app-preferences#61]
Initially preferences are ok, steps:
- adding the plugin
- ionic build ios
- open XCode
- run app
-> OK

Then changing some settings in app-settings.json:
 - ionic build ios
- open XCode
- run app
-> Settings are updated but again in the "wrong" Settings.bundle in the platform root as in https://github.com/apla/me.apla.cordova.app-preferences/issues/60

You have to copy the updated Settings.bundle to /MYPROJECT/Resources manually to get the updated settings.

**Comment by apla** [comment]
Just tested it, works fine. Sometimes after `cordova run ios` app preferences is empty, in this case just remove app and run again.
