### ISSUE TITLE
iOS build broken under 0.7.3 and 0.6.3

### ISSUE THREAD

**Issue by juicysrl** [apla/me.apla.cordova.app-preferences#65]
After installing the plugin,  cordova build ios doesn't produce any output and after_build hooks are not executed. 

The problem seems to be in ios.js, lines 77 to 81:

proj.parse(function (err) {
			err ?
				defer.reject(err) :
				defer.resolve(proj);
		});

The parse function never executes its callback so the promise won't be resolved nor rejected.

**Comment by juicysrl** [comment]
Actually, this is not a problem with the plugin but with node-xcode (https://github.com/alunny/node-xcode) which is used by the plugin. Updating the installed node to the last commit on the master branch of node-xcode repository fixes the problem.

If anyone is in need of this, I don't know how to do it using npm from command line, so I did it 'manually' by cloning the master branch,  going to npm_module folder with root privileges (which in my case was located at /usr/local/lib/node_modules/cordova), deleting existing files in 'xcode' folder (backup first!) and copy-paste from cloned master branch into 'xcode' folder.

**Comment by greenaddress** [comment]
There is a relevant Cordova issue at https://issues.apache.org/jira/browse/CB-10547 - at least for me CordovaLib's dependency was the issue.

**Comment by apla** [comment]
@greenaddress `node-xcode` old version also affecting this plugin and I need to use synchronous version of xcode plist generation. I've added travis-ci to test this issue. As far as I know, latest version works fine regardless of `node-xcode` version
