### ISSUE TITLE
Is there a way to import the Settings.bundle without opening Xcode?

### ISSUE THREAD

**Issue by joncu01** [apla/me.apla.cordova.app-preferences#67]
I'm using the following:
cordova-plugin-app-preferences: 0.7.4
Xcode: 7.1.1
iOS 9.1
Ionic: 1.7.10
Cordova: 5.4.0
I'm using the Ionic CLI to build the my project where after executing "ionic prepare ios" the Settings.bundle is created in platforms/ios.  At this point, I need to open Xcode and manually add the Settings.bundle to my project.  Otherwise, the Settings app on my iOS device will not display my app preferences that I've defined.  Is there a way to do this manual step via the command line so it can be automated?

I noticed that when I do the manual step above that project.pbxproj get modified.  Is there a way to do this via xcodebuild?

**Comment by apla** [comment]
Not sure about ionic, but `cordova` adds `Settings.bundle` just fine to the xcode project file. Try latest version, I've smashed some nasty bugs.

**Comment by apla** [comment]
Sometimes preference pane changes not reflected on app rebuild, like in #76. In that case you'll need to remove app from device and install it again.
