### ISSUE TITLE
String value with quotes does not deserialise properly (ios / osx)

### ISSUE THREAD

**Issue by tripodsan** [apla/me.apla.cordova.app-preferences#72]
fetching a string value that contains quotes does cannot be fetched properly, because the string is not escaped when it is returned via the cordova bridge.

**Comment by tripodsan** [comment]
see PR #73. I didn't check android or blackberry

**Comment by tripodsan** [comment]
...of course it doesn't work either when the value contains backslashes. updated pr.

**Comment by apla** [comment]
Seems like Android is not affected by this issue.

Thank you!

**Comment by apla** [comment]
Published as of 7f7c925565911f9e7903c34a66be871a5fede24a
