### ISSUE TITLE
Im getting TypeError: window.cordova.plugins.appPreferences is undefined

### ISSUE THREAD

**Issue by casper123** [apla/me.apla.cordova.app-preferences#8]
hi,
I've installed your plugin using cordova CLI.. But now im getting this error
I'm getting TypeError: window.cordova.plugins.appPreferences is undefined

I'm using ripple emulator to test.
This is my command
cordova.plugins.appPreferences.store(ok, fail, 'key', 'value');

**Comment by apla** [comment]
test pass on every platform with last commit;
please access plugin via `window.plugins.appPreferences`
