### ISSUE TITLE
iOS preferences issue(?)

### ISSUE THREAD

**Issue by nikolasr200** [apla/me.apla.cordova.app-preferences#89]
I face a "weird" issue over iOS.
Preferences do get generated, and when i ran the app over simulator i can actually see preferences screen.
When i deploy app to a device (ipad) and i select preferences, the preference screen is blank.
Any idea?
I dont seem to get any error..

**Comment by 5type** [comment]
Had the same issue some time ago.
For me it was resolved by closing the app and the settings app and then reopening them.

**Comment by nikolasr200** [comment]
after spending time testing, rolling back to previous version etc, it was solved on my case as well by restarting iOS. It seemed that it had cached something "bad".
