### ISSUE TITLE
What is the size of Preferences that can be stored on each platform ?

### ISSUE THREAD

**Issue by adityasaxena** [apla/me.apla.cordova.app-preferences#94]
Hi @apla . First of all, thanks for making this! 
I'd like to know how much of information you could possibly store on each of the platform. Do you have this information handy ? 
If not, could you provide me any leads to look for myself. Thanks again!!

**Comment by apla** [comment]
I've added direct links to documentation pages, take a look [platforms section](https://github.com/apla/me.apla.cordova.app-preferences/blob/master/README.md#platforms)
