### ISSUE TITLE
Implement clearAll for all platforms

### ISSUE THREAD

**Issue by scurker** [apla/me.apla.cordova.app-preferences#95]
It's not currently publicly documented, but there appears to be a `clearAll` method that clears app preferences on devices. It appears to only be implemented on [Android](https://github.com/apla/me.apla.cordova.app-preferences/blob/version/0.7.7/src/android/AppPreferences.java#L103), with a placeholder ["not implemented" for iOS](https://github.com/apla/me.apla.cordova.app-preferences/blob/version/0.7.7/src/ios/AppPreferences.m#L209).

The main issue is, if you're trying to any kind of cleanup it requires you to know all the keys ahead of time and remove them individually, since there's no easy way to fetch all the keys that you've added. It would be great for scenarios like this if `clearAll` was implemented for every platform.

**Comment by cchen-alison** [comment]
I would love to see this feature. And it would be lovely to get a list of key names we stored as well.

**Comment by apla** [comment]
I've added this functionality in 213eaf37ac460e674b64ca905bb752a890a6e050, but it is not ready for production until I've test it under windows.

**Comment by apla** [comment]
tested under windows, released as 0.99.0
